"""What is not connected yet, and what that means for the client.

A missing secret or a pending setting does not stop an instance: the parts that use it stay
off. That is safe, but "twilio: not set" tells nobody what the client loses. ``missing``
finds where each unset secret is used in the resolved spec (the model, a channel, a
connector, a knowledge source, a trigger) and says, for each one, what it is, what stays off
without it, and how to get it; pending Di-Factory settings get the same treatment.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator
from dataclasses import dataclass, field
from typing import Any

from ..spec.schema import SolutionSpec

# How to get each well-known credential, and what it looks like when stored.
HOW_TO_GET: dict[str, str] = {
    "anthropic": "console.anthropic.com → API Keys (inside a workspace); then"
    " `dif-general-harness secrets set anthropic`",
    "twilio": "the Twilio console home shows the Account SID (AC...) and Auth Token; store"
    " them as `AC...:token` with `dif-general-harness secrets set twilio`",
    "google": "a Google Cloud service account key (JSON) with the Calendar API on, and each"
    " calendar shared with the account's email; `dif-general-harness secrets set google"
    " < key.json`",
    "telegram": "talk to @BotFather in Telegram, /newbot, and store the bot token with"
    " `dif-general-harness secrets set telegram`",
    "email": "the mailbox's SMTP settings as a URL, e.g. smtp://user:pass@smtp.host:587"
    "?from=desk@client.mx; `dif-general-harness secrets set email`",
    "slack": "a Slack app's bot token and signing secret (xoxb-...:secret);"
    " `dif-general-harness secrets set slack`",
    "llm": "the API key of the OpenAI-compatible endpoint the pack runs on;"
    " `dif-general-harness secrets set llm`",
    "admin_token": "generated by the setup on the first deploy; kept in ~/.dif/secrets",
}

CHANNEL_IMPACT = {
    "gateway": "WhatsApp/SMS messages are not received or sent: customers cannot reach the"
    " agent there, and no reminders go out",
    "telegram": "the Telegram bot is off: no messages in or out there",
    "email": "emails are not read or sent (notifications by email included)",
    "slack": "the Slack app is off: no messages in or out there",
    "voice": "phone calls are not answered by the agent",
    "web": "the web chat refuses every message (it is private and needs an access code)",
    "api": "the REST channel refuses every call",
}

CONNECTOR_IMPACT = {
    "google-calendar": "the calendar tools are off: the agent cannot see free slots, book,"
    " move or cancel appointments, so it hands every booking to a person",
}


@dataclass
class Missing:
    name: str  # the secret or setting
    kind: str  # "secret" | "setting"
    what: str  # what it is
    impact: list[str] = field(default_factory=list)  # what stays off without it
    how: str = ""  # how to get it

    def lines(self) -> list[str]:
        out = [f"{self.name} ({self.what})"]
        out += [f"  without it: {i}" for i in self.impact] or ["  without it: nothing visible"]
        if self.how:
            out.append(f"  how to get it: {self.how}")
        return out


def _secret_refs(node: Any, path: tuple[str, ...] = ()) -> Iterator[tuple[str, tuple[str, ...]]]:
    """Every ``{"$secret": name}`` in the resolved data, with where it is."""
    if isinstance(node, dict):
        if set(node) == {"$secret"} and isinstance(node["$secret"], str):
            yield node["$secret"], path
            return
        for key, value in node.items():
            yield from _secret_refs(value, (*path, str(key)))
    elif isinstance(node, list):
        for i, value in enumerate(node):
            yield from _secret_refs(value, (*path, str(i)))


def _impact(spec: SolutionSpec, path: tuple[str, ...]) -> str:
    head = path[0] if path else ""
    if head == "models":
        return "the agent cannot answer at all: every message gets the fallback reply"
    if head == "channels" and len(path) > 1:
        channel = spec.channels.get(path[1])
        kind = channel.type if channel else "?"
        return f"channel {path[1]}: " + CHANNEL_IMPACT.get(kind, "this channel stays off")
    if head == "tools" and len(path) > 2 and path[1] == "config":
        connector = path[2].removeprefix("connectors/")
        effect = CONNECTOR_IMPACT.get(connector, f"the {connector} tools are off")
        return f"{effect}"
    if head == "knowledge":
        corpus = path[2] if len(path) > 2 else "?"
        return f"the {corpus} documents from that source are not synced (the agent knows less)"
    if head == "triggers" and len(path) > 1:
        return f"trigger {path[1]} refuses its calls (nothing it would start happens)"
    if head == "workflows":
        return "a workflow step that uses it fails"
    return "the part that uses it stays off (" + ".".join(path) + ")"


def missing(
    spec: SolutionSpec, data: dict[str, Any], have: Callable[[str], bool],
    pending: list[str] | None = None,
) -> list[Missing]:  # fmt: skip
    """The unset secrets (``have(name)`` is False) and pending settings, with their impact."""
    uses: dict[str, list[str]] = {}
    for name, path in _secret_refs(data):
        if path and path[0] in {"secrets", "variables"}:
            continue
        if path[:1] == ("channels",) and len(path) > 1:
            channel = spec.channels.get(path[1])
            if channel is not None and (channel.enabled is False or channel.enabled == "false"):
                continue  # a channel that is off anyway loses nothing
        impact = _impact(spec, path)
        if impact not in uses.setdefault(name, []):
            uses[name].append(impact)
    out = []
    for name, decl in sorted(spec.secrets.items()):
        if have(name) or name not in uses:
            continue  # set, or declared by the pack but used by nothing in this instance
        how = HOW_TO_GET.get(name, f"`dif-general-harness secrets set {name}`")
        out.append(Missing(name, "secret", decl.description, uses.get(name, []), how))
    for name in pending or []:
        var = spec.variables.get(name)
        what = (var.description if var else None) or "a Di-Factory setting"
        how = f"`dif-general-harness adjust INSTANCE.json --set {name}=VALUE`"
        out.append(Missing(name, "setting", what, [_setting_impact(name)], how))
    return out


def _setting_impact(name: str) -> str:
    if name.startswith("tpl_"):
        return ("WhatsApp only lets a business start a conversation (a reminder, a follow-up)"
                " with a template Meta approved: until its id is set, those messages are not"
                " sent; replies inside a conversation the customer started still work")  # fmt: skip
    return "the feature that uses it runs with a placeholder value"


def report(items: list[Missing]) -> str:
    """Markdown for the client's summary."""
    if not items:
        return ""
    out = ["## Not connected yet, and what that means", ""]
    for item in items:
        out.append(f"- **{item.name}** ({item.what})")
        out += [f"  - Without it: {i}" for i in item.impact or ["nothing visible"]]
        if item.how:
            out.append(f"  - How to get it: {item.how}")
    return "\n".join(out) + "\n"
